version: '3'
services:
  # Apache
  www:
    image: manchenkoff/server
    volumes:
      - ./:/var/www
      - ./config/docker/apache.conf:/etc/apache2/sites-enabled/host.conf
    links:
      - mysql
    ports:
      - 80:80
      - 443:443

  # MySQL
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=geek_project
      - MYSQL_ROOT_PASSWORD=root